window.MUSICAS = [
  {
    "id": "cai-cai-balao",
    "titulo": "Cai Cai Balão",
    "nivel": "facil",
    "origem": "brasileira",
    "tipo": "infantil",
    "subtitulo": "Tradicional brasileira",
    "notas": [
      "G4",
      "G4",
      "F4",
      "E4",
      "G4",
      "G4",
      "F4",
      "E4",
      "G4",
      "A4",
      "G4",
      "F4",
      "E4",
      "D4",
      "D4",
      "E4",
      "F4",
      "D4",
      "E4",
      "F4",
      "D4",
      "E4",
      "F4",
      "G4",
      "A4",
      "G4",
      "F4",
      "E4",
      "D4",
      "C4"
    ],
    "frases": [
      4,
      4,
      6,
      3,
      3,
      3,
      7
    ]
  },
  {
    "id": "ciranda",
    "titulo": "Ciranda Cirandinha",
    "nivel": "facil",
    "origem": "brasileira",
    "tipo": "infantil",
    "subtitulo": "Cantiga tradicional brasileira",
    "notas": [
      "G4",
      "G4",
      "A4",
      "G4",
      "F4",
      "E4",
      "E4",
      "F4",
      "G4",
      "C4",
      "C4",
      "D4",
      "E4",
      "F4",
      "E4",
      "D4",
      "C4"
    ],
    "frases": [
      5,
      4,
      4,
      4
    ]
  },
  {
    "id": "marcha-soldado",
    "titulo": "Marcha Soldado",
    "nivel": "facil",
    "origem": "brasileira",
    "tipo": "infantil",
    "subtitulo": "Cantiga tradicional brasileira",
    "notas": [
      "G4",
      "E4",
      "E4",
      "F4",
      "D4",
      "D4",
      "C4",
      "D4",
      "E4",
      "F4",
      "G4",
      "G4",
      "G4",
      "E4",
      "E4",
      "F4",
      "D4",
      "D4",
      "C4",
      "E4",
      "G4",
      "G4",
      "C4"
    ],
    "frases": [
      6,
      6,
      6,
      5
    ]
  },
  {
    "id": "sapo",
    "titulo": "O Sapo Não Lava o Pé",
    "nivel": "facil",
    "origem": "brasileira",
    "tipo": "infantil",
    "subtitulo": "Cantiga popular brasileira",
    "notas": [
      "C4",
      "C4",
      "D4",
      "E4",
      "E4",
      "D4",
      "C4",
      "E4",
      "G4",
      "G4",
      "A4",
      "G4",
      "F4",
      "E4",
      "D4",
      "C4"
    ],
    "frases": [
      4,
      4,
      4,
      4
    ]
  },
  {
    "id": "atirei",
    "titulo": "Atirei o Pau no Gato",
    "nivel": "facil",
    "origem": "brasileira",
    "tipo": "infantil",
    "subtitulo": "Cantiga tradicional brasileira",
    "notas": [
      "G4",
      "G4",
      "A4",
      "G4",
      "E4",
      "E4",
      "D4",
      "D4",
      "C4",
      "E4",
      "G4",
      "C5",
      "B4",
      "A4",
      "G4"
    ],
    "frases": [
      4,
      4,
      4,
      3
    ]
  },
  {
    "id": "escravos",
    "titulo": "Escravos de Jó",
    "nivel": "medio",
    "origem": "brasileira",
    "tipo": "cultural",
    "subtitulo": "Cantiga tradicional brasileira",
    "notas": [
      "C4",
      "D4",
      "E4",
      "F4",
      "E4",
      "D4",
      "C4",
      "E4",
      "G4",
      "G4",
      "E4",
      "C4",
      "D4",
      "E4",
      "F4",
      "E4",
      "D4",
      "C4"
    ],
    "frases": [
      6,
      6,
      6
    ]
  },
  {
    "id": "peixe-vivo",
    "titulo": "Peixe Vivo",
    "nivel": "medio",
    "origem": "brasileira",
    "tipo": "cultural",
    "subtitulo": "Canção tradicional brasileira",
    "notas": [
      "G4",
      "G4",
      "A4",
      "G4",
      "E4",
      "C4",
      "E4",
      "G4",
      "A4",
      "G4",
      "F4",
      "E4",
      "D4",
      "E4",
      "F4",
      "G4"
    ],
    "frases": [
      4,
      4,
      4,
      4
    ]
  },
  {
    "id": "capelinha",
    "titulo": "Capelinha de Melão",
    "nivel": "facil",
    "origem": "brasileira",
    "tipo": "junina",
    "subtitulo": "Cantiga junina tradicional",
    "notas": [
      "C4",
      "C4",
      "D4",
      "E4",
      "E4",
      "D4",
      "E4",
      "F4",
      "G4",
      "G4",
      "F4",
      "E4",
      "D4",
      "C4"
    ],
    "frases": [
      4,
      4,
      3,
      3
    ]
  },
  {
    "id": "cai-cai",
    "titulo": "Cai, Cai Balão — Completa",
    "nivel": "medio",
    "origem": "brasileira",
    "tipo": "junina",
    "subtitulo": "Versão de estudo da cantiga",
    "notas": [
      "G4",
      "G4",
      "F4",
      "E4",
      "G4",
      "G4",
      "F4",
      "E4",
      "G4",
      "A4",
      "G4",
      "F4",
      "E4",
      "D4",
      "D4",
      "E4",
      "F4",
      "D4",
      "E4",
      "F4",
      "D4",
      "E4",
      "F4",
      "G4",
      "A4",
      "G4",
      "F4",
      "E4",
      "D4",
      "C4"
    ],
    "frases": [
      4,
      4,
      6,
      3,
      3,
      3,
      7
    ]
  },
  {
    "id": "brilha",
    "titulo": "Brilha, Brilha Estrelinha",
    "nivel": "facil",
    "origem": "internacional",
    "tipo": "infantil",
    "subtitulo": "Melodia tradicional",
    "notas": [
      "C4",
      "C4",
      "G4",
      "G4",
      "A4",
      "A4",
      "G4",
      "F4",
      "F4",
      "E4",
      "E4",
      "D4",
      "D4",
      "C4",
      "G4",
      "G4",
      "F4",
      "F4",
      "E4",
      "E4",
      "D4",
      "G4",
      "G4",
      "F4",
      "F4",
      "E4",
      "E4",
      "D4",
      "C4",
      "C4",
      "G4",
      "G4",
      "A4",
      "A4",
      "G4",
      "F4",
      "F4",
      "E4",
      "E4",
      "D4",
      "D4",
      "C4"
    ],
    "frases": [
      7,
      7,
      7,
      7,
      7,
      7
    ]
  },
  {
    "id": "parabens",
    "titulo": "Parabéns pra Você",
    "nivel": "facil",
    "origem": "internacional",
    "tipo": "comemorativa",
    "subtitulo": "Melodia popular de aniversário",
    "notas": [
      "G4",
      "G4",
      "A4",
      "G4",
      "C5",
      "B4",
      "G4",
      "G4",
      "A4",
      "G4",
      "D4",
      "C4",
      "G4",
      "G4",
      "G4",
      "E4",
      "C4",
      "B4",
      "A4",
      "F4",
      "F4",
      "E4",
      "C4",
      "D4",
      "C4"
    ],
    "frases": [
      6,
      6,
      7,
      6
    ]
  },
  {
    "id": "frere",
    "titulo": "Frère Jacques",
    "nivel": "facil",
    "origem": "internacional",
    "tipo": "infantil",
    "subtitulo": "Canção tradicional francesa",
    "notas": [
      "C4",
      "D4",
      "E4",
      "C4",
      "C4",
      "D4",
      "E4",
      "C4",
      "E4",
      "F4",
      "G4",
      "E4",
      "F4",
      "G4",
      "G4",
      "A4",
      "G4",
      "F4",
      "E4",
      "C4",
      "G4",
      "A4",
      "G4",
      "F4",
      "E4",
      "C4",
      "C4",
      "G4",
      "C4",
      "C4",
      "G4",
      "C4"
    ],
    "frases": [
      4,
      4,
      3,
      3,
      6,
      6,
      3,
      3
    ]
  },
  {
    "id": "mary",
    "titulo": "Mary Had a Little Lamb",
    "nivel": "facil",
    "origem": "internacional",
    "tipo": "infantil",
    "subtitulo": "Canção infantil tradicional",
    "notas": [
      "E4",
      "D4",
      "C4",
      "D4",
      "E4",
      "E4",
      "E4",
      "D4",
      "D4",
      "D4",
      "E4",
      "G4",
      "G4",
      "E4",
      "D4",
      "C4",
      "D4",
      "E4",
      "E4",
      "E4",
      "E4",
      "D4",
      "D4",
      "E4",
      "D4",
      "C4"
    ],
    "frases": [
      7,
      6,
      7,
      6
    ]
  },
  {
    "id": "row-boat",
    "titulo": "Row, Row, Row Your Boat",
    "nivel": "facil",
    "origem": "internacional",
    "tipo": "infantil",
    "subtitulo": "Canção tradicional",
    "notas": [
      "C4",
      "C4",
      "C4",
      "D4",
      "E4",
      "E4",
      "D4",
      "E4",
      "F4",
      "G4",
      "C5",
      "C5",
      "C5",
      "G4",
      "G4",
      "G4",
      "E4",
      "E4",
      "E4",
      "C4",
      "C4",
      "C4",
      "G4",
      "F4",
      "E4",
      "D4",
      "C4"
    ],
    "frases": [
      5,
      5,
      6,
      6,
      5
    ]
  },
  {
    "id": "old-macdonald",
    "titulo": "Old MacDonald",
    "nivel": "medio",
    "origem": "internacional",
    "tipo": "infantil",
    "subtitulo": "Canção tradicional",
    "notas": [
      "C4",
      "C4",
      "C4",
      "G4",
      "A4",
      "A4",
      "G4",
      "E4",
      "E4",
      "D4",
      "D4",
      "C4",
      "G4",
      "C4",
      "C4",
      "C4",
      "G4",
      "A4",
      "A4",
      "G4",
      "E4",
      "E4",
      "D4",
      "D4",
      "C4"
    ],
    "frases": [
      6,
      6,
      6,
      6
    ]
  },
  {
    "id": "london",
    "titulo": "London Bridge",
    "nivel": "facil",
    "origem": "internacional",
    "tipo": "infantil",
    "subtitulo": "Canção tradicional inglesa",
    "notas": [
      "G4",
      "A4",
      "G4",
      "F4",
      "E4",
      "F4",
      "G4",
      "D4",
      "E4",
      "F4",
      "E4",
      "F4",
      "G4",
      "G4",
      "A4",
      "G4",
      "F4",
      "E4",
      "F4",
      "G4",
      "D4",
      "G4",
      "E4",
      "C4"
    ],
    "frases": [
      7,
      6,
      6,
      5
    ]
  },
  {
    "id": "hot-cross",
    "titulo": "Hot Cross Buns",
    "nivel": "facil",
    "origem": "internacional",
    "tipo": "infantil",
    "subtitulo": "Melodia tradicional",
    "notas": [
      "E4",
      "D4",
      "C4",
      "E4",
      "D4",
      "C4",
      "C4",
      "C4",
      "C4",
      "C4",
      "D4",
      "D4",
      "D4",
      "D4",
      "E4",
      "D4",
      "C4"
    ],
    "frases": [
      3,
      3,
      4,
      4,
      3
    ]
  },
  {
    "id": "ode",
    "titulo": "Ode à Alegria",
    "nivel": "facil",
    "origem": "internacional",
    "tipo": "classica",
    "subtitulo": "Beethoven · tema principal",
    "notas": [
      "E4",
      "E4",
      "F4",
      "G4",
      "G4",
      "F4",
      "E4",
      "D4",
      "C4",
      "C4",
      "D4",
      "E4",
      "E4",
      "D4",
      "D4",
      "E4",
      "E4",
      "F4",
      "G4",
      "G4",
      "F4",
      "E4",
      "D4",
      "C4",
      "C4",
      "D4",
      "E4",
      "D4",
      "C4",
      "C4"
    ],
    "frases": [
      8,
      7,
      8,
      7
    ]
  },
  {
    "id": "mozart",
    "titulo": "Ah! Vous dirai-je, Maman",
    "nivel": "medio",
    "origem": "internacional",
    "tipo": "classica",
    "subtitulo": "Melodia usada por Mozart em variações",
    "notas": [
      "C4",
      "C4",
      "G4",
      "G4",
      "A4",
      "A4",
      "G4",
      "F4",
      "F4",
      "E4",
      "E4",
      "D4",
      "D4",
      "C4"
    ],
    "frases": [
      7,
      7
    ]
  },
  {
    "id": "saints",
    "titulo": "When the Saints Go Marching In",
    "nivel": "medio",
    "origem": "internacional",
    "tipo": "cultural",
    "subtitulo": "Spiritual tradicional",
    "notas": [
      "C4",
      "E4",
      "F4",
      "G4",
      "C4",
      "E4",
      "F4",
      "G4",
      "C4",
      "E4",
      "F4",
      "G4",
      "E4",
      "C4",
      "E4",
      "D4",
      "E4",
      "E4",
      "D4",
      "C4",
      "C4",
      "E4",
      "G4",
      "G4",
      "F4",
      "E4",
      "F4",
      "G4",
      "E4",
      "C4",
      "D4",
      "C4"
    ],
    "frases": [
      4,
      4,
      6,
      6,
      6,
      6
    ]
  },
  {
    "id": "susanna",
    "titulo": "Oh! Susanna",
    "nivel": "medio",
    "origem": "americana",
    "tipo": "cultural",
    "subtitulo": "Stephen Foster · tema",
    "notas": [
      "C4",
      "D4",
      "E4",
      "G4",
      "G4",
      "A4",
      "G4",
      "E4",
      "C4",
      "D4",
      "E4",
      "E4",
      "D4",
      "C4",
      "D4",
      "C4",
      "D4",
      "E4",
      "G4",
      "G4",
      "A4",
      "G4",
      "E4",
      "C4",
      "D4",
      "E4",
      "E4",
      "D4",
      "D4",
      "C4"
    ],
    "frases": [
      8,
      7,
      8,
      7
    ]
  },
  {
    "id": "yankee",
    "titulo": "Yankee Doodle",
    "nivel": "medio",
    "origem": "americana",
    "tipo": "cultural",
    "subtitulo": "Canção tradicional americana",
    "notas": [
      "C4",
      "C4",
      "D4",
      "E4",
      "C4",
      "E4",
      "D4",
      "C4",
      "C4",
      "D4",
      "E4",
      "F4",
      "E4",
      "D4",
      "C4",
      "B4",
      "C5",
      "C4",
      "C4",
      "D4",
      "E4",
      "C4",
      "B4",
      "A4",
      "G4"
    ],
    "frases": [
      8,
      7,
      5,
      5
    ]
  },
  {
    "id": "jingle",
    "titulo": "Jingle Bells",
    "nivel": "facil",
    "origem": "internacional",
    "tipo": "natalina",
    "subtitulo": "Canção natalina tradicional",
    "notas": [
      "E4",
      "E4",
      "E4",
      "E4",
      "E4",
      "E4",
      "E4",
      "G4",
      "C4",
      "D4",
      "E4",
      "F4",
      "F4",
      "F4",
      "F4",
      "F4",
      "E4",
      "E4",
      "E4",
      "E4",
      "D4",
      "D4",
      "E4",
      "D4",
      "G4"
    ],
    "frases": [
      6,
      5,
      5,
      5,
      4
    ]
  },
  {
    "id": "silent",
    "titulo": "Noite Feliz",
    "nivel": "medio",
    "origem": "internacional",
    "tipo": "natalina",
    "subtitulo": "Melodia de Franz Xaver Gruber",
    "notas": [
      "G4",
      "A4",
      "G4",
      "E4",
      "G4",
      "A4",
      "G4",
      "E4",
      "D4",
      "D4",
      "B4",
      "C5",
      "C5",
      "G4",
      "A4",
      "A4",
      "C5",
      "B4",
      "A4",
      "G4",
      "A4",
      "G4",
      "E4"
    ],
    "frases": [
      4,
      4,
      6,
      5,
      4
    ]
  },
  {
    "id": "greensleeves",
    "titulo": "Greensleeves",
    "nivel": "dificil",
    "origem": "internacional",
    "tipo": "tradicional",
    "subtitulo": "Melodia tradicional inglesa · adaptação",
    "notas": [
      "A4",
      "C5",
      "D4",
      "E4",
      "F4",
      "E4",
      "D4",
      "B4",
      "G4",
      "A4",
      "B4",
      "C5",
      "A4",
      "A4",
      "G4",
      "A4",
      "B4",
      "G4",
      "E4",
      "E4",
      "A4",
      "C5",
      "D4",
      "E4",
      "F4",
      "E4",
      "D4",
      "B4",
      "G4",
      "A4",
      "B4",
      "C5",
      "B4",
      "A4",
      "G4",
      "F4",
      "E4",
      "D4",
      "C4"
    ],
    "frases": [
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      4
    ]
  },
  {
    "id": "scale",
    "titulo": "Escala Dó Maior",
    "nivel": "facil",
    "origem": "exercicio",
    "tipo": "tecnica",
    "subtitulo": "Exercício de coordenação",
    "notas": [
      "C4",
      "D4",
      "E4",
      "F4",
      "G4",
      "A4",
      "B4",
      "C5",
      "B4",
      "A4",
      "G4",
      "F4",
      "E4",
      "D4",
      "C4"
    ],
    "frases": [
      8,
      7
    ]
  },
  {
    "id": "tercas",
    "titulo": "Passeio em Terças",
    "nivel": "medio",
    "origem": "exercicio",
    "tipo": "tecnica",
    "subtitulo": "Exercício de intervalos",
    "notas": [
      "C4",
      "E4",
      "D4",
      "F4",
      "E4",
      "G4",
      "F4",
      "A4",
      "G4",
      "B4",
      "A4",
      "C5",
      "B4",
      "G4",
      "A4",
      "F4",
      "G4",
      "E4",
      "F4",
      "D4",
      "E4",
      "C4"
    ],
    "frases": [
      6,
      6,
      5,
      5
    ]
  },
  {
    "id": "arpejo",
    "titulo": "Arpejo de Dó",
    "nivel": "medio",
    "origem": "exercicio",
    "tipo": "tecnica",
    "subtitulo": "Exercício de agilidade",
    "notas": [
      "C4",
      "E4",
      "G4",
      "C5",
      "G4",
      "E4",
      "C4",
      "E4",
      "G4",
      "C5",
      "B4",
      "G4",
      "E4"
    ],
    "frases": [
      4,
      3,
      3,
      3
    ]
  },
  {
    "id": "zigzag",
    "titulo": "Zigue-Zague",
    "nivel": "dificil",
    "origem": "exercicio",
    "tipo": "tecnica",
    "subtitulo": "Exercício de precisão",
    "notas": [
      "C4",
      "G4",
      "D4",
      "A4",
      "E4",
      "B4",
      "F4",
      "C5",
      "B4",
      "E4",
      "A4",
      "D4",
      "G4",
      "C4"
    ],
    "frases": [
      7,
      7
    ]
  },
  {
    "id": "velocidade",
    "titulo": "Desafio de Velocidade",
    "nivel": "dificil",
    "origem": "exercicio",
    "tipo": "tecnica",
    "subtitulo": "Exercício rápido",
    "notas": [
      "C4",
      "D4",
      "E4",
      "F4",
      "G4",
      "A4",
      "B4",
      "C5",
      "B4",
      "A4",
      "G4",
      "F4",
      "E4",
      "D4",
      "C4",
      "E4",
      "G4",
      "B4",
      "A4",
      "F4",
      "D4",
      "C4"
    ],
    "frases": [
      8,
      7,
      7
    ]
  },
  {
    "id": "sinos",
    "titulo": "Sinos de Natal",
    "nivel": "facil",
    "origem": "internacional",
    "tipo": "natalina",
    "subtitulo": "Exercício inspirado em motivos natalinos",
    "notas": [
      "E4",
      "G4",
      "G4",
      "A4",
      "G4",
      "E4",
      "D4",
      "E4",
      "G4",
      "C5",
      "B4",
      "A4",
      "G4"
    ],
    "frases": [
      5,
      4,
      4
    ]
  },
  {
    "id": "cantiga1",
    "titulo": "Roda de Cantiga",
    "nivel": "facil",
    "origem": "brasileira",
    "tipo": "cultural",
    "subtitulo": "Exercício em estilo de cantiga de roda",
    "notas": [
      "C4",
      "D4",
      "E4",
      "G4",
      "E4",
      "D4",
      "C4",
      "E4",
      "F4",
      "G4",
      "A4",
      "G4",
      "E4",
      "C4"
    ],
    "frases": [
      4,
      4,
      3,
      3
    ]
  },
  {
    "id": "festa-junina",
    "titulo": "Festa Junina",
    "nivel": "medio",
    "origem": "brasileira",
    "tipo": "junina",
    "subtitulo": "Exercício em clima de festa junina",
    "notas": [
      "G4",
      "A4",
      "G4",
      "E4",
      "D4",
      "E4",
      "G4",
      "A4",
      "C5",
      "B4",
      "A4",
      "G4",
      "E4",
      "D4",
      "C4"
    ],
    "frases": [
      5,
      5,
      5
    ]
  },
  {
    "id": "samba-study",
    "titulo": "Balanço Brasileiro",
    "nivel": "medio",
    "origem": "brasileira",
    "tipo": "samba",
    "subtitulo": "Exercício melódico com balanço brasileiro",
    "notas": [
      "C4",
      "E4",
      "G4",
      "A4",
      "G4",
      "E4",
      "D4",
      "F4",
      "A4",
      "G4",
      "E4",
      "D4",
      "C4"
    ],
    "frases": [
      4,
      4,
      5
    ]
  },
  {
    "id": "baiao-study",
    "titulo": "Passos de Baião",
    "nivel": "medio",
    "origem": "brasileira",
    "tipo": "baiao",
    "subtitulo": "Exercício melódico em clima nordestino",
    "notas": [
      "C4",
      "E4",
      "F4",
      "G4",
      "A4",
      "G4",
      "F4",
      "E4",
      "D4",
      "F4",
      "G4",
      "A4",
      "G4",
      "E4",
      "C4"
    ],
    "frases": [
      5,
      5,
      5
    ]
  },
  {
    "id": "rock-study",
    "titulo": "Primeiro Rock",
    "nivel": "medio",
    "origem": "internacional",
    "tipo": "pop-rock",
    "subtitulo": "Exercício melódico pop-rock",
    "notas": [
      "E4",
      "E4",
      "G4",
      "A4",
      "G4",
      "E4",
      "D4",
      "E4",
      "G4",
      "B4",
      "A4",
      "G4",
      "E4"
    ],
    "frases": [
      4,
      4,
      5
    ]
  },
  {
    "id": "pop-study",
    "titulo": "Melodia Pop",
    "nivel": "medio",
    "origem": "internacional",
    "tipo": "pop-rock",
    "subtitulo": "Exercício melódico pop",
    "notas": [
      "C4",
      "E4",
      "G4",
      "A4",
      "G4",
      "E4",
      "F4",
      "A4",
      "C5",
      "B4",
      "A4",
      "G4",
      "E4",
      "D4"
    ],
    "frases": [
      5,
      5,
      4
    ]
  },
  {
    "id": "memoria1",
    "titulo": "Memória 1",
    "nivel": "facil",
    "origem": "exercicio",
    "tipo": "tecnica",
    "subtitulo": "Sequência curta para memorizar",
    "notas": [
      "C4",
      "D4",
      "E4",
      "G4",
      "E4",
      "D4",
      "C4"
    ],
    "frases": [
      4,
      3
    ]
  },
  {
    "id": "memoria2",
    "titulo": "Memória 2",
    "nivel": "medio",
    "origem": "exercicio",
    "tipo": "tecnica",
    "subtitulo": "Sequência média para memorizar",
    "notas": [
      "G4",
      "E4",
      "F4",
      "D4",
      "E4",
      "C4",
      "D4",
      "G4",
      "A4",
      "G4"
    ],
    "frases": [
      5,
      5
    ]
  },
  {
    "id": "memoria3",
    "titulo": "Memória 3",
    "nivel": "dificil",
    "origem": "exercicio",
    "tipo": "tecnica",
    "subtitulo": "Sequência longa para memorizar",
    "notas": [
      "C4",
      "G4",
      "E4",
      "A4",
      "F4",
      "B4",
      "G4",
      "C5",
      "A4",
      "F4",
      "D4",
      "E4",
      "C4"
    ],
    "frases": [
      5,
      4,
      4
    ]
  },
  {
    "id": "eco",
    "titulo": "Eco Musical",
    "nivel": "facil",
    "origem": "exercicio",
    "tipo": "tecnica",
    "subtitulo": "Repita cada pequena frase",
    "notas": [
      "C4",
      "D4",
      "E4",
      "C4",
      "D4",
      "E4",
      "G4",
      "A4",
      "G4",
      "G4",
      "A4",
      "G4"
    ],
    "frases": [
      3,
      3,
      3,
      3
    ]
  },
  {
    "id": "saltos",
    "titulo": "Saltos de Notas",
    "nivel": "dificil",
    "origem": "exercicio",
    "tipo": "tecnica",
    "subtitulo": "Treino de intervalos maiores",
    "notas": [
      "C4",
      "G4",
      "C5",
      "E4",
      "A4",
      "D4",
      "B4",
      "F4",
      "C5",
      "G4",
      "E4",
      "C4"
    ],
    "frases": [
      4,
      4,
      4
    ]
  },
  {
    "id": "descida",
    "titulo": "Escada Descendente",
    "nivel": "facil",
    "origem": "exercicio",
    "tipo": "tecnica",
    "subtitulo": "Treino descendente",
    "notas": [
      "C5",
      "B4",
      "A4",
      "G4",
      "F4",
      "E4",
      "D4",
      "C4"
    ],
    "frases": [
      4,
      4
    ]
  },
  {
    "id": "subida",
    "titulo": "Escada Ascendente",
    "nivel": "facil",
    "origem": "exercicio",
    "tipo": "tecnica",
    "subtitulo": "Treino ascendente",
    "notas": [
      "C4",
      "D4",
      "E4",
      "F4",
      "G4",
      "A4",
      "B4",
      "C5"
    ],
    "frases": [
      4,
      4
    ]
  },
  {
    "id": "alternadas",
    "titulo": "Notas Alternadas",
    "nivel": "medio",
    "origem": "exercicio",
    "tipo": "tecnica",
    "subtitulo": "Coordenação e leitura",
    "notas": [
      "C4",
      "E4",
      "D4",
      "F4",
      "E4",
      "G4",
      "F4",
      "A4",
      "G4",
      "B4",
      "A4",
      "C5"
    ],
    "frases": [
      4,
      4,
      4
    ]
  },
  {
    "id": "finale",
    "titulo": "Grande Desafio",
    "nivel": "dificil",
    "origem": "exercicio",
    "tipo": "tecnica",
    "subtitulo": "Mistura de escalas e saltos",
    "notas": [
      "C4",
      "E4",
      "G4",
      "C5",
      "B4",
      "G4",
      "A4",
      "F4",
      "G4",
      "E4",
      "F4",
      "D4",
      "E4",
      "C4",
      "D4",
      "F4",
      "A4",
      "C5",
      "B4",
      "G4",
      "E4",
      "C4"
    ],
    "frases": [
      6,
      6,
      5,
      5
    ]
  },
  {
    "id": "manha",
    "titulo": "Bom Dia, Piano",
    "nivel": "facil",
    "origem": "exercicio",
    "tipo": "livre",
    "subtitulo": "Melodia original para aquecimento",
    "notas": [
      "C4",
      "E4",
      "G4",
      "E4",
      "F4",
      "A4",
      "G4",
      "E4",
      "D4",
      "C4"
    ],
    "frases": [
      5,
      5
    ]
  },
  {
    "id": "chuva",
    "titulo": "Pingos de Chuva",
    "nivel": "facil",
    "origem": "exercicio",
    "tipo": "livre",
    "subtitulo": "Melodia original curta",
    "notas": [
      "G4",
      "E4",
      "G4",
      "E4",
      "F4",
      "D4",
      "F4",
      "D4",
      "E4",
      "C4"
    ],
    "frases": [
      5,
      5
    ]
  },
  {
    "id": "viagem",
    "titulo": "Pequena Viagem",
    "nivel": "medio",
    "origem": "exercicio",
    "tipo": "livre",
    "subtitulo": "Melodia original de estudo",
    "notas": [
      "C4",
      "D4",
      "E4",
      "G4",
      "A4",
      "G4",
      "F4",
      "E4",
      "D4",
      "F4",
      "G4",
      "E4",
      "C4"
    ],
    "frases": [
      5,
      4,
      4
    ]
  },
  {
    "id": "noite",
    "titulo": "Noite no Teclado",
    "nivel": "medio",
    "origem": "exercicio",
    "tipo": "livre",
    "subtitulo": "Melodia original de estudo",
    "notas": [
      "A4",
      "G4",
      "E4",
      "D4",
      "E4",
      "G4",
      "A4",
      "C5",
      "B4",
      "G4",
      "E4",
      "C4"
    ],
    "frases": [
      4,
      4,
      4
    ]
  }
];